import home from "./home"
import about from "./about"
import eqity from "./eqity"
import demate from "./demate"
import luxurious from "./luxurious"
import insurence from "./insurence"
import contact from "./contact"
import fund from "./fund" 
import post from "./post"
import news from "./news"
export const schemaTypes = [home,about,eqity,demate, luxurious, insurence, contact , fund , post,news]
